#### 异常

* 异常︰指的是程序在执行过程中，出现的非正常情况，如果不处理最终会导致JvM的非正常停止。

* 异常指的并不是语法错误和逻辑错误。语法错了，编译不通过，不会产生字节码文件，根本不能运行。
   代码逻辑错误，只是没有得到想要的结果，例如:a与b的和，你写成了a-b

* ```java
  	public static void main(String[] args) {
    		// TODO 自动生成的方法存根
          System.out.println(11/0);
    	}
  Exception in thread "main" java.lang.ArithmeticException: / by zero
  	at exception.test1.main(test1.java:7)
  
  ```

* 常见异常

  *  检查型异常
  * 运行时异常
  * 错误ERROR

* 异常体系结构

  * Java把异常当作对象来处理，并定义一个基类java.lang.Throwable作为所有异常的超类。在Java API中已经定义了许多异常类，这些异常类分为两大类，错误Error和异常Exception.
  * Throwable父类是Object，错误和异常都是可以抛出的
  * <img src="%E5%BC%82%E5%B8%B8.assets/1689417779351.png" alt="1689417779351" style="zoom:80%;" />

* ERROR

  * Error类对象由Java虚拟机生成并抛出,大多数错误与代码编写者所执行的操作无关。他是Java虚拟机无法解决的严重问题。如:JVM系统内部错误、资源耗尽等严重情况。一般不编写针对性的代码进行处理。例如栈内存溢出(StackOverflowError)，堆内存溢出(OutOfMemoryError)

    ```java
        public static void main(String[] args) {
            //栈溢出
            main(args);
    
            //堆溢出
            byte[]arr=new byte[1024*1024*100];//如果堆的空间不满100m，就会报错
        }
    ```

    

  * Java虚拟机运行错误(Virtual MachineError)，当JVM不再有继续执行操作所需的内存资源时，将出现 OutOfMemoryError。这些异常发生时，Java虚拟机(JVM)一般会选择线程终止;

  * 还有发生在虚拟机试图执行应用时，如类定义错误(NoClassDefFoundError)、链接错误(LinkageError)。这些错误是不可查的，因为它们在应用程序的控制和处理能力之外，而且绝大多数是程序运行时不允许出现的状况。

* Exception（编译时异常就是代码写try catch或者往上抛的，运行时异常）**所有的异常都是运行时才报错，因为异常需要new异常对象。之所以叫编译时异常，是因为编译器能够发现。**

  * 在Exception分支中有一个重要的子类RuntimeException(运行时异常)
    
  * **编译时异常：就是在写代码中必须的处理，不处理就报错的，又称为受检异常**
    
    * ClassNotFoundException(找不到类）等异常，这些异常是不检查异常，程序中可以选择捕获处理，也可以不处理。
    
      ```java
       public void test(){
              Class.forName("java.lang.String");
          }
      ```
    
    * FileNotFoundException
    
    * IOException
    
      ```java
          @Test
          public void test(){
              File file=new File("AA.txt");
              //FileNotFoundException
              FileInputStream inputStream=new FileInputStream(file);
              //IOException
              int data=inputStream.read();
              while (data!=-1){
                  System.out.println((char)data);
                  //IOException
                  data=inputStream.read();
              }
              //IOException
              inputStream.close();
          }
      ```
    
      
    
  * **运行时异常：编写程序时可以处理，也可以不处理**
    
    * ArrayIndexOutOfBoundsException(数组下标越界)
    
    * NullPointerException(空指针异常)
    
    * ArithmeticException(算术异常)
      
    * MissingResourceException(丢失资源)
      
    ```java
          @Test
          public void test(){
              int num=10;
              System.out.println(num/0);
          }
    ```
    
    * ClassCastException类转换异常
    
      ```java
         public void test(){
              Object o=new String();
              Date  date= (Date) o;
          }
      ```
    
      
    
    * InputMismatchException
    
      ```java
       @Test
          public void test(){
              Scanner scanner=new Scanner(System.in);
              int i = scanner.nextInt();
              System.out.println(i);
              //然后控制台输入了一个字符串，就会报这个错误
          }
      ```
    
      
    
    * NumberFormatException字符串转数字
    
      ```java
       String str="abc";
              Integer.parseInt(str);
      ```
    
      
    
  * 这些异常一般是由程序逻辑错误引起的，程序应该从逻辑角度尽可能避免这类异常的发生;

  * Error和Exception的区别: **Error通常是灾难性的致命的错误，是程序无法控制和处理的，当出现这些异常时，Java虚拟机(JVM)一般会选择终止线程;**==Exception通常情况下是可以被程序处理的，并且在程序中应该尽可能的去处理这些异常。==

  * 分为编译器异常(编译成字节码)和运行时异常

    ![1693643177923](%E5%BC%82%E5%B8%B8.assets/1693643177923.png)

    * 编译时期异常(即checked异常、受检异常)∶在代码编译阶段，编译器就能明确警示当前代码可能发生(不是一定发生）x异常，并明确督促程序员提前编写处理它的代码。如果程序员没有编写对应的异常处理代码，则编译器就会直接判定编译失败，从而不能生成字节码文件。通常，这类异常的发生不是由程序员的代码引起的，或者不是靠加简单判断就可以避免的，例如:FileNotFoundException (文件找不到异常)。
    * 运行时期异常(即runtime异常、unchecked异常、非受检异常)︰在代码编译阶段，编译器完全不做任何检查，无论该异常是否会发生，编译器都不给出任何提示。只有等代码运行起来并确实发生了xx异常，它才能被发现。通常，这类异常是由程序员的代码编写不当引起的，只要稍加判断，或者细心检查就可以避免。

* Throwable常用的方法

   * public void printStackTrace():打印异常的详细信息
   * public String getMessage():获取发生异常的原因

* 异常机制

  *  检查异常

  * 捕获异常

    * ```java
      try{//监视区域
          
      }catch{//捕获异常
          
      }
      
      	public static void main(String[] args) {
      		// TODO 自动生成的方法存根
              try {
              	System.out.println(11/0);
      		} catch (ArithmeticException e) {
      			// TODO: handle exception
      			System.out.println("异常");
      		}finally {//处理善后工作
      			System.out.println("finally");
      		}
      	}
      ```

    * **可以有多个catch，而且建议多个catch，这样可以精细捕获异常，方便后期处理。但是有顺序，catch的捕获从上到小是范围越来越大，否则会报错**

      ![1704369018608](%E5%BC%82%E5%B8%B8.assets/1704369018608.png)
      
    * finally一般用于IO流关闭，数据库连接，socket来凝结，在使用后，必须显示关闭的操作，负责垃圾回收器不会回收的这些资源，会造成内存泄漏。他是执行一定要执行的代码块，哪怕是前面有return，他也会执行，唯一的例外,使用System.exit(0)来终止当前正在运行的Java虚拟机

      ```java
          public static int test(String str){
              try {
                  Integer.parseInt(str);
                  return 1;
              }catch (NumberFormatException e){
                  e.printStackTrace();
                  return -1;
              }finally {
                  //有return也会执行
                  System.out.println("结束");
                  return 0;//有这句话，无论执行哪个代码块，最后返回值都是0
              }
          }
      ```

      

    * **catch可以写多个，层层递进，把最大的异常类写在最后面，他只会执行一个异常**

    * idea快捷键ctrl+alt+t

    * **jdk8新特性**

      ```java
              try {
                  FileInputStream inputStream=new FileInputStream("aa");
              }catch (FileNotFoundException | ArithmeticException e){
      
              }
      ```

      

  * try catch是可选的,finally不能单独存在，try不能省略，其它都可以省略

  * `try...catch`

  *  `try...finally`，**只要进去try,finally就一定会执行，哪怕是try里有return，finally执行后才能return。但是try有System.exit(0)，finally就不会执行了，因为jvm已经结束了;**

  *  `try...catch..finally`

     ```java
         public static int test2(int num){
             try {
                 return num;
             }
             finally {
                 //有return也会执行
                 //return ++num;
                 ++num;
             }
         }
     //即finally和catch他们可以任意一个搭配try
     ```

     

* 抛出异常

  * 通过throw手动抛出异常对象，不满足指定条件的情况下，主动使用throw+异常类对象方式抛出异常

  * ```java
    	public static void main(String[] args) {
      		// TODO 自动生成的方法存根
           int a=11;
           int b=0;
           if(b==0) {
        	   throw new ArithmeticException();
           }
    }
    class AA {
        public void test(int i)  {
        if (i>0){
    	            System.out.println(i);
    	        }
    	        else {
    	            throw new RuntimeException("输入异常");
    	        }
    	    }
    	}
    	  
    ```
    
  * 也可以在方法上抛出异常,**throws**，public void test() throws，即在代码执行的过程中，一旦出现异常，自动生成异常类对象，并经此对象抛出，抛出后面的代码就不会在执行
  
     * 从编译是否能通过的角度看，看成是给出了异常万一要是出现时候的解决方案。此方案就是，继续向上抛出(throws)。但是，此throws的方式，仅是将可能出现的异常抛给了此方法的调用者。此调用者仍然需要考虑如何处理相关异常。从这个角度来看，throws的方式不算是真正意义上处理了异常。
  
        * **方法重写的要求：子类重写的方法抛出的异常类型可以与父类被重写的方法抛出的异常类型相同，或是父类被重写的方法抛出异常类型的子类。如果父类的方法没有抛异常，则子类重写也不能抛异常（上转型会出问题），对于重写只能使用try catch解决，但是可以抛运行时异常，即RuntimeException，但写不写无所谓。即重写的要求只针对于编译时异常****
  
           ```java
           public class test1 {
               public static void main(String[] args) {
                  AA aa=new BB();
                   try {
                       aa.test();
                       //编译器会按照父类的捕获IOException e，但是抛异常抛的是子类的异常,如果比父类的大会捕获不到
                   } catch (IOException e) {
                       e.printStackTrace();
                   }
               }
           }
           class AA {
               public void test() throws IOException {
           
               }
           }
           class BB extends AA{
               //和分类相同或者子类，为啥不能子类，因为可能有上转型，即子类的对象给父类，在try catch时捕获的父类定义的异常，如果比父类的大会捕获不到
               public void test() throws IOException{
           
               }
           }
           ```
  
           
  
* 抓异常，通过try,catch抓，或throws，自动抛本质也是throw

  * Exception e对象怎么被创建呢，一定是aa里有throw new Exception("输入异常")了，这两个对象是一样的，源码也是这样的。
  * 这两个异常要么一样，要么外面那个是里面的父类

  ```java
  public class test1 {
      public static void main(String[] args) {
          AA aa = new AA();
          try {
              aa.test(10);
          } catch (Exception e) {
              e.printStackTrace();//处理该方法抛出的异常
          }
      }
  }
  class AA {
      public void test(int i) throws Exception {//把else的里的异常抛出去
          if (i>0){
              System.out.println(i);
          }
          else {
              //如果抛的时运行时异常不用处理，只处理编译时异常
              throw new Exception("输入异常");
          }
      }
  }
  ```

  

* 异常关键字

  * try,catch,finally,throw, throws

* 自定义异常

  * 创建一个类继承于现有的异常体系，Exception或RuntimeException

  * 通常提供几个重载的构造器

  * 提供一个全局常量static final long serialVersionUID

    ```java
    public class test1 {
        public static void main(String[] args) {
            BB bb = new BB();
            try {
                bb.test(10);
            } catch (AA aa) {
                aa.printStackTrace();
            }
        }
    }
    class AA extends Exception {
        static final long serialVersionUID = -3387516993124229949L;
        public AA(){
    
        }
        public AA(String msg){
            super(msg);
        }
        public AA(String message, Throwable cause)
        {
            super(message, cause);
        }
    }
    class BB{
        public void test(int i) throws AA {
            if (i>0){
                System.out.println(i);
            }
            else {
                throw new AA("异常");
            }
        }
    }
    ```

    * aa.printStackTrace();等价于System.out.println(aa.getMessage());

  * 自定义异常：使得报错信息更明确

* try catch是可以嵌套使用的

   ```java
       public static int test2(int num){
           try {
               return num;
           }catch (NumberFormatException e){
               e.printStackTrace();
               return num--;
           }finally {
               try {
                   
               }catch (Exception e){
                   
               }
           }
       }
   ```

   

* 经验总结：

  * 处理运行时异常时，采用逻辑去合理规避同时辅助try-catch处理
  * 资源回收，重写 try-catch finally
  * 开发中，方法a中依次调用了方法b,c,d等方法，方法b,c,d之间是递进关系。此时，如果方法b,c,d中有异常，我们通常选择使用throws，而方法a中通常选择使用try-catch-finally.
  * 在多重catch块后面，可以加一个catch (Exception)来处理可能会被遗漏的异常
  * 对于不确定的代码，也可以加上 try-catch，处理潜在的异常
  * 尽量去处理异常，切忌只是简单地调用printStackTrace()去打印输出
  * 具体如何处理异常，要根据不同的业务需求和异常类型去决定
  * 尽量添加finally语句块去释放占用的资源

##### 面试题

* finally用法

  ```java
  public class test1 {
      public static void main(String[] args) {
         test2(10);
      }
      public static int test2(int num){
          try {
              return num;
          }catch (NumberFormatException e){
              e.printStackTrace();
              return num--;
          }finally {
              //有return也会执行
              //return ++num;
              ++num;
          }
      }
  }
  10
  ```

  ```java
  public class Final {
      public static void main(String[] args) {
          System.out.println(m());
      }
      public static int m(){
          int i=100;
          try {
              return i;
          }
          finally {
              i++;
          }
      }
  }
  100
  ```

  * java语法规则（有一些规则是不能破坏的，一旦这么说了，就必须这么做!):

    * **java中有一条这样的规则：方法体中的代码必须遵循自上而下顺序做次逐行执行(（亘古不变的语法!)****

    * **return语句一旦执行，整个方法必须结束(亘古不变的语法!)**

    * 原理：把class进行反编译，这样能保证不违背这两条规则

      ```
      public class Final {
          public Final() {
          }
      
          public static void main(String[] args) {
              System.out.println(m());
          }
      
          public static int m() {
              int i = 100;
      
              int var1;
              try {
                  var1 = i;
              } finally {
                  ++i;
              }
      
              return var1;
          }
      }
      ```

      

* final,finally,finalize区别：finalize是方法名。java技术允许使用finalize（）方法在垃圾收集器将对象从内存中清除出去之前做必要的清理工作。这个方法是由垃圾收集器在确定这个对象没有被引用时对这个对象调用的。它是在object类中定义的，因此所有的类都继承了它。子类覆盖finalize（）方法以整理系统资源或者被执行其他清理工作。finalize（）方法是在垃圾收集器删除对象之前对这个对象调用的。 

* throw和throws区别
  
  * 上游排污，下游治污。 **throws用于方法头，表示的只是异常的申明，而throw用于方法内部，抛出的是`异常对象`** 



##### 练习题

```java
public class test1 {
    public static void main(String[] args) {
        BB bb = new BB("aa",10);
        System.out.println(bb.toString());
        BB bb2 = new BB("bb",-1);
        System.out.println(bb2.toString());
    }
}
class NoLifeValueException extends RuntimeException {
    static final long serialVersionUID = -3387516993124229949L;
    public NoLifeValueException(){

    }
    public NoLifeValueException(String msg){
        super(msg);
    }
}
class BB{
    private String name;
    private int lifeValue;

    public BB() {
    }

    public BB(String name, int lifeValue){
        this.name = name;
        setLifeValue(lifeValue);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getLifeValue() {
        return lifeValue;
    }

    public void setLifeValue(int lifeValue)  {
        if (lifeValue<0){
            throw new NoLifeValueException("生命不能为负数: "+lifeValue);
        }
        this.lifeValue = lifeValue;
    }

    @Override
    public String toString() {
        return "BB{" +
                "name='" + name + '\'' +
                ", lifeValue=" + lifeValue +
                '}';
    }
}


```

